In [1]:
import pandas as pd
import numpy as np
import sklearn as skl

In [2]:
df =pd.read_parquet(r'C:\Users\mdjsa\OneDrive\Documentos\Marquinho\06_POS_GRADUACAO\03a_FASE\alunos_enriquecido.parquet').drop(['ANO'], axis=1)

In [3]:
df.head()

,ano,id_municipio,id_escola,id_aluno,rede,alfabetizado,pct_in_biblioteca,pct_in_sala_leitura,pct_in_internet,pct_in_laboratorio_informatica,...,qtd_pes_acima_meio_sm_media,qtd_pes_pob_min,qtd_pes_baixa_renda_min,qtd_pes_acima_meio_sm_min,qtd_pes_pob_max,qtd_pes_baixa_renda_max,qtd_pes_acima_meio_sm_max,qtd_pes_pob_desvio_padrao,qtd_pes_baixa_renda_desvio_padrao,qtd_pes_acima_meio_sm_desvio_padrao
0,2023,330070,60025977,33014516,Municipal,1,0.357143,0.649351,0.993506,0.311688,...,15008.3,59740,16977,9130,68077,20868,19074,3069.361036,1507.987699,4148.806041
1,2023,312160,60021971,31008498,Municipal,1,0.804878,0.121951,0.975610,0.487805,...,7293.5,11687,8354,4478,14705,9407,9245,1315.642370,380.101171,1992.772510
2,2023,315780,60018571,31151092,Estadual,1,0.765432,0.197531,1.000000,0.358025,...,20555.5,46111,25722,10641,60477,27113,26625,6171.184418,489.561527,6795.470849
3,2023,420480,60035456,42032360,Municipal,1,0.777778,0.083333,1.000000,0.583333,...,5802.6,5868,4693,3917,7909,5432,6906,869.306550,278.190662,1242.301198
4,2023,420480,60035456,42032357,Municipal,1,0.777778,0.083333,1.000000,0.583333,...,5802.6,5868,4693,3917,7909,5432,6906,869.306550,278.190662,1242.301198

In [4]:
print(df.dtypes)

ano                                      int32
id_municipio                             int64
id_escola                                int64
id_aluno                                 int64
rede                                    object
alfabetizado                             int64
pct_in_biblioteca                      float64
pct_in_sala_leitura                    float64
pct_in_internet                        float64
pct_in_laboratorio_informatica         float64
pct_in_agua_potavel                    float64
pct_in_energia_inexistente             float64
pct_in_esgoto_inexistente              float64
pct_in_alimentacao                     float64
pct_in_acessibilidade_corrimao         float64
pct_in_acessibilidade_elevador         float64
pct_in_acessibilidade_pisos_tateis     float64
pct_in_acessibilidade_vao_livre        float64
pct_in_acessibilidade_rampas           float64
pct_in_acessibilidade_sinal_sonoro     float64
pct_in_acessibilidade_sinal_tatil      float64
pct_in_acessibilidade_sinal_visual     float64
pct_in_banheiro_pne                    float64
pct_in_material_ped_infantil           float64
pct_in_material_ped_cientifico         float64
pct_in_material_ped_jogos              float64
pct_in_material_ped_artisticas         float64
pct_in_material_ped_multimidia         float64
pct_in_educacao_indigena               float64
qt_mat_bas_media                       float64
qt_salas_media                         float64
n_escolas                                int64
qtd_pes_pob_media                      float64
qtd_pes_baixa_renda_media              float64
qtd_pes_acima_meio_sm_media            float64
qtd_pes_pob_min                          int64
qtd_pes_baixa_renda_min                  int64
qtd_pes_acima_meio_sm_min                int64
qtd_pes_pob_max                          int64
qtd_pes_baixa_renda_max                  int64
qtd_pes_acima_meio_sm_max                int64
qtd_pes_pob_desvio_padrao              float64
qtd_pes_baixa_renda_desvio_padrao      float64
qtd_pes_acima_meio_sm_desvio_padrao    float64
dtype: object

In [5]:
colunas_id = ["id_aluno", "id_escola", "id_municipio", "ano"]
coluna_target = "alfabetizado"

colunas_categoricas = ["rede"]

colunas_numericas = [
    col for col in df.columns
    if col not in colunas_id + colunas_categoricas + [coluna_target]
]

print(f"Numéricas: {len(colunas_numericas)}")
print(f"Categóricas: {len(colunas_categoricas)}")

Numéricas: 38
Categóricas: 1

In [6]:
from sklearn.model_selection import train_test_split

X = df[colunas_numericas + colunas_categoricas]
y = df[coluna_target]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y  # garante mesma proporção de alfabetizado/não-alfabetizado nos dois conjuntos
)

print(f"Treino: {X_train.shape}")
print(f"Teste: {X_test.shape}")
print(f"Proporção do target (treino):\n{y_train.value_counts(normalize=True)}")
print(f"Proporção do target (teste):\n{y_test.value_counts(normalize=True)}")

Treino: (2684657, 39)
Teste: (671165, 39)
Proporção do target (treino):
alfabetizado
1    0.591369
0    0.408631
Name: proportion, dtype: float64
Proporção do target (teste):
alfabetizado
1    0.591369
0    0.408631
Name: proportion, dtype: float64

In [7]:
df = df.drop(colunas_id, axis=1)

In [8]:
df.head()

,rede,alfabetizado,pct_in_biblioteca,pct_in_sala_leitura,pct_in_internet,pct_in_laboratorio_informatica,pct_in_agua_potavel,pct_in_energia_inexistente,pct_in_esgoto_inexistente,pct_in_alimentacao,...,qtd_pes_acima_meio_sm_media,qtd_pes_pob_min,qtd_pes_baixa_renda_min,qtd_pes_acima_meio_sm_min,qtd_pes_pob_max,qtd_pes_baixa_renda_max,qtd_pes_acima_meio_sm_max,qtd_pes_pob_desvio_padrao,qtd_pes_baixa_renda_desvio_padrao,qtd_pes_acima_meio_sm_desvio_padrao
0,Municipal,1,0.357143,0.649351,0.993506,0.311688,0.993506,0.0,0.00000,0.720779,...,15008.3,59740,16977,9130,68077,20868,19074,3069.361036,1507.987699,4148.806041
1,Municipal,1,0.804878,0.121951,0.975610,0.487805,0.975610,0.0,0.02439,0.853659,...,7293.5,11687,8354,4478,14705,9407,9245,1315.642370,380.101171,1992.772510
2,Estadual,1,0.765432,0.197531,1.000000,0.358025,1.000000,0.0,0.00000,0.802469,...,20555.5,46111,25722,10641,60477,27113,26625,6171.184418,489.561527,6795.470849
3,Municipal,1,0.777778,0.083333,1.000000,0.583333,1.000000,0.0,0.00000,0.861111,...,5802.6,5868,4693,3917,7909,5432,6906,869.306550,278.190662,1242.301198
4,Municipal,1,0.777778,0.083333,1.000000,0.583333,1.000000,0.0,0.00000,0.861111,...,5802.6,5868,4693,3917,7909,5432,6906,869.306550,278.190662,1242.301198

In [11]:
import sys
sys.path.append("..")
from src.modeling.treinamento_modelo import treinar_modelo
from src.evaluation.avaliacao_modelo import avaliar_modelo


resultado = treinar_modelo(
    df=df,
    colunas_numericas=colunas_numericas,
    colunas_categoricas=colunas_categoricas,
    coluna_target="alfabetizado",
)

metricas = avaliar_modelo(resultado)

ModuleNotFoundError: No module named 'lightgbm'